

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package basiclibrary;
import java.util.Arrays;

public class Library {

    public static void main(String[] args) {

//        System.out.println(Arrays.toString(roll(5)));
//        int[] testArray = new int[] {1,2,3,4,5,6,7,99};
//        System.out.println(calculateAverage(testArray));

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        System.out.println(Arrays.toString(lowestAverage(weeklyMonthTemperatures)));

    }

    public static int[] roll(int n) {
        int[] rollArray = new int[n];

        for (int i = 0 ; i < n ; i++) {
            rollArray[i] = (int) (Math.random() * 6 + 1);
        }
        return rollArray;
    }

    public static boolean containsDuplicates(int[] inputArray) {
        for (int i = 0 ; i < inputArray.length - 1 ; i++) {
            for (int j = i + 1 ; j < inputArray.length ; j++) {
                if (inputArray[i] == inputArray[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static float calculateAverage(int[] inputArray) {
        int sum = 0;

        for (int i = 0 ; i < inputArray.length ; i++) {
            sum += inputArray[i];
        }
        return (float) sum / inputArray.length;
    }

    public static int[] lowestAverage(int[][] arrayOfArrays) {

        int lowestIndex = 0;
        float lowestAvg = calculateAverage(arrayOfArrays[lowestIndex]);

        for (int i = 1 ; i < arrayOfArrays.length ; i++) {
            if (calculateAverage(arrayOfArrays[i]) < lowestAvg) {
                lowestIndex = i;
                lowestAvg = calculateAverage(arrayOfArrays[lowestIndex]);
            }
        }
        return arrayOfArrays[lowestIndex];
    }

}
